<?php
$menus = [['auth_activation_attempts', 'auth_activation_attempts'],['auth_groups', 'auth_groups'],['auth_groups_permissions', 'auth_groups_permissions'],['auth_groups_users', 'auth_groups_users'],['auth_logins', 'auth_logins'],['auth_permissions', 'auth_permissions'],['auth_reset_attempts', 'auth_reset_attempts'],['auth_tokens', 'auth_tokens'],['auth_users_permissions', 'auth_users_permissions'],['culinary', 'culinary'],['culinary_detail_facility', 'culinary_detail_facility'],['culinary_facility', 'culinary_facility'],['culinary_gallery', 'culinary_gallery'],['detail_package', 'detail_package'],['detail_service_package', 'detail_service_package'],['event', 'event'],['event_category', 'event_category'],['event_gallery', 'event_gallery'],['event_video', 'event_video'],['homestay', 'homestay'],['homestay_detail_facility', 'homestay_detail_facility'],['homestay_facility', 'homestay_facility'],['homestay_gallery', 'homestay_gallery'],['migrations', 'migrations'],['package', 'package'],['package_day', 'package_day'],['service_package', 'service_package'],['souvenir_detail_facility', 'souvenir_detail_facility'],['souvenir_facility', 'souvenir_facility'],['souvenir_gallery', 'souvenir_gallery'],['souvenir_place', 'souvenir_place'],['tourism_category', 'tourism_category'],['tourism_detail_facility', 'tourism_detail_facility'],['tourism_facility', 'tourism_facility'],['tourism_gallery', 'tourism_gallery'],['tourism_object', 'tourism_object'],['tourism_video', 'tourism_video'],['users', 'users'],['village', 'village'],['worship_category', 'worship_category'],['worship_detail_facility', 'worship_detail_facility'],['worship_facility', 'worship_facility'],['worship_gallery', 'worship_gallery'],['worship_place', 'worship_place'],
];
?>
<ul class="nav flex-column">
    <?php foreach ($menus as $m) : ?>
        <li class="nav-item">
            <a class="nav-link" href="<?= base_url() . '/' . $m[0] ?>"> <?= $m[1] ?></a>
        </li>
    <?php endforeach; ?>
</ul>



<?php 
/* End of file views/layout/sidebar.php */
/* Location: ./app/views/layout */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2023-07-07 09:50:26 */
?>