<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\Detail_service_packageModel;

class Detail_service_package extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $PageData;
	protected $Model; //Default Models Of this Controler
	protected $pager;
	public function __construct()
	{
		$this->Model = new Detail_service_packageModel(); //Set Default Models Of this Controler
		$this->PageData = $this->attributePage(); //Attribute Of Page
		$pager = \Config\Services::pager();
	}

	//ATRIBUTE THIS PAGE
	private function attributePage()
	{
		return  [
			'title' => 'LigatCode | Detail_service_package',
			'app' => 'LigatCode',
		];
	}

	//INDEX 
	public function index()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'data' => $this->Model->paginate(5, 'paging'),
			'pager' => $this->Model->pager
		];
		return view('detail_service_package/index_detail_service_package', $data);
	}

	//READ
	public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read',
			'data' => $this->Model->getData($id) //find on data
		];
		return view('detail_service_package/read_detail_service_package', $data);
	}

	//CREATE
	public function create()
	{
		$db = \Config\Database::connect();
		$query   = $db->query('SELECT id_package, name FROM package');
		$query1 = $db->query('SELECT id_service_package, name FROM service_package');
		$hasil = array(
			'type'    => 'FeatureCollection',
			'features' => array()
		);
		foreach ($query->getResultArray() as $row) {
			$features = array(
				'type' => 'Feature',
				'properties' => array(
					'id_package' => $row['id_package'],
					'name' => $row['name'],
				)
			);
			array_push($hasil['features'], $features);
		}
		$hasil1 = array(
			'type'    => 'FeatureCollection',
			'features' => array()
		);
		foreach ($query1->getResultArray() as $row) {
			$features = array(
				'type' => 'Feature',
				'properties' => array(
					'id_service_package' => $row['id_service_package'],
					'name' => $row['name'],
				)
			);
			array_push($hasil1['features'], $features);
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create ',
			'action' => site_url('detail_service_package/create_action'),
			'data' =>   [
				'id_service_package' => set_value('id_service_package'),
				'id_package' => set_value('id_package'),
				'status' => set_value('status'),
			],
			'status' => 'Not Visible',
			'package' => $hasil,
			'service_package' => $hasil1
		];
		return view('detail_service_package/form_detail_service_package', $data);
	}

	//ACTION CREATE
	public function create_action()
	{
		$db = \Config\Database::connect();
		$data = [
			'id_service_package' => $this->request->getVar('id_service_package'),
			'id_package' => $this->request->getVar('id_package'),
			'status' => $this->request->getVar('status'),

		];

		$id_service_package = $this->request->getVar('id_service_package');
		$id_package = $this->request->getVar('id_package');
		$status = $this->request->getVar('status');

		$query = $db->query("INSERT INTO `detail_service_package` (`id_service_package`,`id_package`, `status`) VALUES ('" . $id_service_package . "','" . $id_package . "','" . $status . "');");
		// // $this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/package'));
	}

	//UPDATE
	public function update($id)
	{
		$db = \Config\Database::connect();
		$query   = $db->query('SELECT * FROM package ');
		$hasil_package = array(
			'type'    => 'FeatureCollection',
			'features' => array()
		);

		foreach ($query->getResultArray() as $row) {
			$features = array(
				'type' => 'Feature',

				'properties' => array(
					'id_package' => $row['id_package'],
					'name' => $row['name'],

				)
			);
			array_push($hasil_package['features'], $features);
		}
		$dataFind = $this->Model->getData($id);
		if ($dataFind == false) {
			return redirect()->to(base_url('/Detail_service_package'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'detail_service_package/update_action',
			'data' => $this->Model->getData($id),
			'status' => 'Visible',
			'package' => $hasil_package
		];
		session()->setFlashdata('message', 'Update Record Success');
		return view('detail_service_package/form_detail_service_package', $data);
	}

	//ACTION UPDATE
	public function update_action()
	{
		$id_service_package = $this->request->getVar('id_service_package');
		$id_package = $this->request->getVar('id_package');
		$status = $this->request->getVar('status');


		$db = \Config\Database::connect();
		$query   = $db->query("UPDATE `detail_service_package` SET `status` = '" . $status . "' WHERE `detail_service_package`.`id_service_package` = '" . $id_service_package . "' AND `detail_service_package`.`id_package` = '" . $id_package . "'; ");

		return redirect()->to(base_url('package'));
		// echo "UPDATE `detail_service_package` SET `status` = '" . $status . "' WHERE `detail_service_package`.`id_service_package` = '" . $id_service_package . "' AND `detail_service_package`.`id_package` = '" . $id_package . "'; ";
	}

	//DELETE
	public function delete($id)
	{
		$row = $this->Model->getData(['id_service_package' => $id]);
		if ($row) {
			$this->Model->delete($id);
			session()->setFlashdata('message', 'Delete Record Success');
		} else {
			session()->setFlashdata('message', 'Record Not Found');
		}

		return redirect()->to(base_url('/detail_service_package'));
	}

	//RULES
	public function _rules()
	{
		$this->form_validation->set_rules('id_package', 'id package', 'trim|required');
		$this->form_validation->set_rules('status', 'status', 'trim|required');

		$this->form_validation->set_rules('id_service_package', 'id_service_package', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}
}

/* End of file Detail_service_package.php */
 /* Location: ./app/controllers/Detail_service_package.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2023-07-05 07:21:46 */