<?php

namespace App\Models;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use CodeIgniter\Model;

class Detail_service_packageModel extends Model
{
    protected $table      = 'detail_service_package';
    protected $primaryKey = 'id_service_package';
    //To help protect against Mass Assignment Attacks, the Model class requires 
    //that you list all of the field names that can be changed during inserts and updates
    // https://codeigniter4.github.io/userguide/models/model.html#protecting-fields
    protected $allowedFields = ['id_service_package', 'id_package', 'status'];

    // GET ALL DATA
    public function getData($id_service_package = false, $id_package = false)
    {
        if ($id_service_package == false) {
            $builder = $this->db->table('detail_service_package');
            $builder->select('id_service_package,id_package,status', false);
            // $builder->join('event_gallery', 'event.id=event_gallery.id', 'LEFT');
            $query = $builder->get();
            return $query->getResult();
        }
        $builder = $this->db->table('detail_service_package');
        $builder->select('id_service_package,id_package,status', false);
        $builder->where('id_service_package', $id_service_package);
        $builder->where('id_package', $id_package);

        $query = $builder->get();
        return $query->getResult();
    }
}

/* End of file Detail_service_packageModel.php */
/* Location: ./app/models/Detail_service_packageModel.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2023-07-05 07:21:46 */