<?php

namespace App\Models;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use CodeIgniter\Model;

class Detail_packageModel extends Model
{
    protected $table      = 'detail_package';
    protected $primaryKey = 'id_package';
    //To help protect against Mass Assignment Attacks, the Model class requires 
    //that you list all of the field names that can be changed during inserts and updates
    // https://codeigniter4.github.io/userguide/models/model.html#protecting-fields
    protected $allowedFields = ['id_package', 'day', 'activity', 'activity_type', 'id_object', 'description'];

    // GET ALL DATA
    public function getData($id_package = false, $day = false, $activity = false)
    {
        if ($id_package == false) {
            $builder = $this->db->table('detail_package');
            $builder->select('id_package, day, activity, activity_type, id_object, description', false);
            // $builder->join('event_gallery', 'event.id=event_gallery.id', 'LEFT');
            $query = $builder->get();
            return $query->getResult();
        }
        $builder = $this->db->table('detail_package');
        $builder->select('id_package, day, activity, activity_type, id_object, description', false);
        $builder->where('id_package', $id_package);
        $builder->where('day', $day);
        $builder->where('activity', $activity);
        $query = $builder->get();
        return $query->getResult();
    }
}

/* End of file Detail_packageModel.php */
/* Location: ./app/models/Detail_packageModel.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2023-07-04 15:03:32 */