<?php

namespace App\Models;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use CodeIgniter\Model;

class PackageModel extends Model
{
    protected $table      = 'package';
    protected $primaryKey = 'id_package';
    //To help protect against Mass Assignment Attacks, the Model class requires 
    //that you list all of the field names that can be changed during inserts and updates
    // https://codeigniter4.github.io/userguide/models/model.html#protecting-fields
    protected $allowedFields = ['id_package', 'name', 'min_capaity', 'contact_person', 'description', 'brosur_url', 'price', 'custom'];

    // GET ALL DATA
    public function getData($id_package = false)
    {
        if ($id_package == false) {
            $builder = $this->db->table('package');
            $builder->select('id_package, name, min_capaity, contact_person, description, brosur_url, price,custom', false);
            $builder->where('custom', "0");
            // $builder->join('event_gallery', 'event.id=event_gallery.id', 'LEFT');
            $query = $builder->get();
            return $query->getResult();
        }
        $builder = $this->db->table('package');
        $builder->select('id_package, name, min_capaity, contact_person, description, brosur_url, price,custom', false);
        $builder->where('id_package', $id_package);
        $query = $builder->get();
        return $query->getResult();



        // return $this->db->where($this->primaryKey, $id)->first();
    }
}

/* End of file PackageModel.php */
/* Location: ./app/models/PackageModel.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2023-07-04 15:05:39 */