<?php

namespace App\Models;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use CodeIgniter\Model;

class Package_dayModel extends Model
{
    protected $table      = 'package_day';
    protected $primaryKey = 'id_package';
    //To help protect against Mass Assignment Attacks, the Model class requires 
    //that you list all of the field names that can be changed during inserts and updates
    // https://codeigniter4.github.io/userguide/models/model.html#protecting-fields
    protected $allowedFields = ['id_package', 'day', 'description'];

    // GET ALL DATA
    public function getData($id = false)
    {
        if ($id == false) {
            return $this->findAll();
        }
        return $this->db->where($this->primaryKey, $id)->first();
    }
    public function getSpecial($id_package = false, $day = false)
    {
        if ($id_package == false) {
            $builder = $this->db->table('package_day');
            $builder->select('id_package, day, description', false);
            $builder->join('package', 'package.id_package=package_day.id_package');
            $builder->where('pakcage.custom', "0");
            // $builder->join('event_gallery', 'event.id=event_gallery.id', 'LEFT');
            $query = $builder->get();
            return $query->getResult();
            // return $this->findAll();
        }

        $builder = $this->db->table('package_day');
        $builder->select('id_package, day, description', false);
        $builder->where('id_package', $id_package);
        $builder->where('day', $day);
        $query = $builder->get();
        return $query->getResult();
        // return $this->db->where($this->primaryKey, $id)->first();
    }
}

/* End of file Package_dayModel.php */
/* Location: ./app/models/Package_dayModel.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2023-07-04 15:05:49 */