<?php

namespace App\Models;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Controllers\Service_package;
use CodeIgniter\Model;

class Service_packageModel extends Model
{
    protected $table      = 'service_package';
    protected $primaryKey = 'id_service_package';
    //To help protect against Mass Assignment Attacks, the Model class requires 
    //that you list all of the field names that can be changed during inserts and updates
    // https://codeigniter4.github.io/userguide/models/model.html#protecting-fields
    protected $allowedFields = ['id_service_package', 'name'];

    // GET ALL DATA
    public function getData($id_service_package = false)
    {
        if ($id_service_package == false) {
            $builder = $this->db->table('service_package');
            $builder->select('id_service_package, name', false);
            $query = $builder->get();
            return $query->getResult();
        }
        $builder = $this->db->table('service_package');
        $builder->select('id_service_package, name', false);
        $builder->where('id_service_package', $id_service_package);
        $query = $builder->get();
        return $query->getResult();
    }
}

/* End of file Service_packageModel.php */
/* Location: ./app/models/Service_packageModel.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2023-07-04 15:06:09 */